# Generated by Django 4.2.10 on 2024-10-12 11:41

from django.db import migrations, models
import django.utils.timezone
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userpayment',
            options={'get_latest_by': 'modified'},
        ),
        migrations.AddField(
            model_name='userpayment',
            name='created',
            field=django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='created'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userpayment',
            name='modified',
            field=django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified'),
        ),
        migrations.AddField(
            model_name='userpayment',
            name='site_name',
            field=models.CharField(default='project_1', max_length=255),
            preserve_default=False,
        ),
    ]
