# Generated by Django 4.2.10 on 2024-08-27 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='username',
            field=models.CharField(default='test', max_length=150, unique=True),
            preserve_default=False,
        ),
    ]
