# Generated by Django 4.2.10 on 2024-08-27 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentications', '0003_alter_customuser_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='site_name',
            field=models.CharField(default='localhost', max_length=150),
            preserve_default=False,
        ),
    ]
