# Generated by Django 4.2.10 on 2024-10-12 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentications', '0005_alter_customuser_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='site_name',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
