# Generated by Django 4.2.10 on 2024-10-12 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentications', '0006_alter_customuser_site_name'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='customuser',
            unique_together=set(),
        ),
    ]
