# Generated by Django 4.2.10 on 2024-10-12 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentications', '0008_alter_customuser_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='site_name',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(max_length=150),
        ),
    ]
